config/routes.rb
BTVProject::Application.routes.draw do

  get "schedule/index"

  match "/board" => "board#index"
	match "/schedule" => "schedule#index"

  resources :videos
  get "sessions/new"

  get "sessions/create"

  get "sessions/failure"

  resources :authentications

  resources :posts

  match "about" => "home#about"
  match "contact" => "home#contact"
  match "shows" => "home#shows"
  match "schedule" => "home#schedule"
  match "join" => "home#join"
  match "Juncture" => "home#Juncture"
  match "BTV_News" => "home#BTV_News"
  match "Binghamton_Bro_Code" => "home#Binghamton_Bro_Code"
  match "BTV_Mornings" => "home#BTV_Mornings"
  match "Cup_of_Joe" => "home#Cup_of_Joe"
  match "Common_Occurances" => "home#Common_Occurances"
  match "Gametime!" => "home#Gametime!"
  match "What_4" => "home#What_4"
  match "Comics_Anonymous" => "home#Comics_Anonymous"

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  resources :identities

  namespace :admin do
    root :to => "dashboard#index"
    resources :users, :except => ['new', 'create', 'edit'] do
      resource :board_info, :except => ['new', 'create', 'edit']
    end
    resources :videos, :except => ['new', 'create', 'edit'] do
      member do
        put "approve"
      end
    end
    match "/pending" => "videos#pending", :as => "pending_videos"
  end

  root :to => "home#index"

end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :string(255)
#  url         :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Video < ActiveRecord::Base
  belongs_to :User
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController

  include AdminModule

  def index
#    @videos = Video.where("pending = 0").all
  end

  def pending
#    @videos = Video.where("pending = 1").all
  end

  def show
#    @video = Video.find(params[:id])
  end

  def update
    # This one depends on whether the edit view stays the same
#    @video = Video.find(params[:id])
    redirect_to admin_video_path(params[:id])
  end

  def approve
#    @video = Video.find(params[:id])
#    if (@video.pending = 1)
#      @video.pending = 0
#      #Send email to author that their video was approved.
#    else
#      @video.pending = 1
#      #Send email to author saying that their video was moved deapproved.
#    end
    redirect_to admin_video_path(params[:id])
  end

  def destroy
#    @video = Video.find(params[:id])
#    if @video.pending = 1
#      #Send email to author saying that their video was denied.
#    end
#    @video.destroy
    redirect_to admin_videos_path
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/videos/index.html.haml
.container
  .span10.offset1
    %h1.text-center
      Approved User Videos
    %table.table.table-hover
      %thead
        %tr
          %th Title
          %th Description
          %th URL
      %tbody
        %tr
          %td= link_to "Video 1", admin_video_path(0)
          %td This is the first video.
          %td= link_to "Here", "http://www.google.com"

    <br>
    = link_to "Back to Admin", admin_root_path

app/views/admin/videos/pending.html.haml
.container
  .span10.offset1
    %h1.text-center
      Unapproved User Videos
    %table.table.table-hover
      %thead
        %tr
          %th Title
          %th Description
          %th URL
      %tbody
        %tr
          %td= link_to "Unapproved Video 1", admin_video_path(1)
          %td This is the second video.
          %td= link_to "Here", "http://www.google.com"

    <br>
    = link_to "Back to Admin", admin_root_path

app/views/admin/videos/show.html.haml
.container
  .span10.offset1
    %h1.text-center
      = "Unapproved Video Information"
    = form_tag admin_video_path(params[:id]), :method => :put do
      = label_tag "title", "Title"
      = text_field_tag "title", "Unapproved Video"
      = label_tag "description", "Description"
      = text_area_tag "description", "This is the second video"
      = label_tag "url", "URL"
      = url_field_tag "url", "http://www.google.com"
      = label_tag "pending", "Approved?"
      = text_field_tag "pending", "No", :disabled => true
      %br
      = submit_tag "Submit Changes", :confirm => "Change this video's information?"

  %br
  = button_to "Approve", approve_admin_video_path(params[:id]), :method => :put,
    :confirm => "An email will be sent to the author.\nApprove this video?"

  %br
  = link_to "Back to Dashboard", admin_root_path