config/routes.rb
BTVProject::Application.routes.draw do

  get "schedule/index"

  match "/board" => "board#index"
	match "/schedule" => "schedule#index"

  resources :videos
  get "sessions/new"

  get "sessions/create"

  get "sessions/failure"

  resources :authentications

  resources :posts

  match "about" => "home#about"
  match "contact" => "home#contact"
  match "shows" => "home#shows"
  match "schedule" => "home#schedule"
  match "join" => "home#join"
  match "Juncture" => "home#Juncture"
  match "BTV_News" => "home#BTV_News"
  match "Binghamton_Bro_Code" => "home#Binghamton_Bro_Code"
  match "BTV_Mornings" => "home#BTV_Mornings"
  match "Cup_of_Joe" => "home#Cup_of_Joe"
  match "Common_Occurances" => "home#Common_Occurances"
  match "Gametime!" => "home#Gametime!"
  match "What_4" => "home#What_4"
  match "Comics_Anonymous" => "home#Comics_Anonymous"

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  resources :identities

  namespace :admin do
    root :to => "dashboard#index"
    resources :users, :except => ['new', 'create', 'edit'] do
      resource :board_info, :except => ['new', 'create', 'edit']
    end
    resources :videos, :except => ['new', 'create', 'edit'] do
      member do
        put "approve"
      end
    end
    match "/pending" => "videos#pending", :as => "pending_videos"
  end

  root :to => "home#index"

end

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    %title B-TV - Administration
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
    :css
      body {
          padding-top: 60px;
          padding-bottom: 40px;
      }
    %meta{:content => "", :name => "description"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    = stylesheet_link_tag "bootstrap.min"
    = stylesheet_link_tag "bootstrap-responsive.min"
    = stylesheet_link_tag "main"
    = javascript_include_tag "modernizr-2.6.2-respond-1.1.0.min"

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a#ham_btn.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand#BTV_logo{:href => "/"}
            %img{:src => "/assets/BTV.jpg"} 
          .nav-collapse.collapse#navbar
            %ul.nav
              %li{:class => @home_active}
                %a{:href => "/"} Home
              %li{:class => @about_active}
                %a{:href => "/about"} About
              %li{:class => @board_active}
                %a{:href => "/board"} Board
              %li{:class => @shows_active}
                %a{:href => "/shows"} Shows
              %li{:class => @schedule_active}
                %a{:href => "/schedule"} Schedule
              %li{:class => @join_active}
                %a{:href => "/join"} Joins
              %li.divider-vertical
            %ul.nav.pull-right
              %li.divider-vertical
              %li= link_to "Dashboard", admin_root_path
              %li= link_to "Users", admin_users_path
              %li= link_to "User Videos", admin_videos_path
              %li= link_to "Pending Videos", admin_pending_videos_path
          / /.nav-collapse

    - if flash[:notice]
      #notice.span10= flash[:notice]
    - elsif flash[:warning]
      #warning.span10= flash[:warning]
 
    = yield
  %hr
  %footer
    %p © B-TV
    %script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"}
    = javascript_include_tag "bootstrap.min"
    = javascript_include_tag "plugins"
    = javascript_include_tag "main"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title B-TV 
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}/
    :css
      body {
          padding-top: 60px;
          padding-bottom: 40px;
      }
    %meta{:content => "", :name => "description"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    = stylesheet_link_tag "bootstrap.min"
    = stylesheet_link_tag "bootstrap-responsive.min"
    = stylesheet_link_tag "main"

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a#ham_btn.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .nav-collapse.collapse#navbar
            %ul.nav
              %li{:class => @home_active}
                %a{:href => "/"} Home
              %li{:class => @about_active}
                %a{:href => "/about"} About
              %li{:class => @board_active}
                %a{:href => "/board"} Board
              %li{:class => @shows_active}
                %a{:href => "/shows"} Shows
              %li{:class => @schedule_active}
                %a{:href => "/schedule"} Schedule
              %li{:class => @login_active}
                %a{:href => "/login"} Login
          / /.nav-collapse
 
    = yield
  %hr
  %footer
    %p © B-TV
    %script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"}
    = javascript_include_tag "modernizr-2.6.2-respond-1.1.0.min"
    = javascript_include_tag "bootstrap.min"
    = javascript_include_tag "plugins"
    = javascript_include_tag "main"
    :javascript
      // Google Analytics tracking
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-40230836-1', 'herokuapp.com');
      ga('send', 'pageview');